# Generated by Django 5.0.6 on 2024-07-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
